project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

bibliography: references.bib  

format:
  html:
    self-contained: True
    comments:
      hypothesis: true
  docx: default
  jats: default

execute:
  freeze: true
